### PR TITLE
adds child_frame_id to odom msg

### PR DESCRIPTION
**Pull request by efernandez**
This is specified at http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html

### CODE REVIEW

**Comment by po1** [comment]
I don't think `base_footprint` is that universal. Even though it seems that PR2 uses it, [REP 105](http://www.ros.org/reps/rep-0105.html) states that there should be a direct transform `/odom -> /base_link`.

As such, I would make this a parameter, and the default value should be `/base_link`

**Comment by bmagyar** [comment]
+1 to base_link

**Comment by efernandez** [comment]
I just added a 'base_frame_id' param which default to 'base_link'.

I've also added the parameter for the REEM robots, setting it to base_footprint.

**Comment by po1** [comment]
Thanks! Please update the [wiki page](http://wiki.ros.org/diff_drive_controller) with this new parameter.
[EDIT] after this gets merged upstream, that is.

+1

**Comment by bmagyar** [comment]
I'll keep this tab open to remind me :)

**Comment by adolfo-rt** [comment]
...and send it upstream please

**Comment by po1** [comment]
Only the second commit needs to be sent upstream, I'll extract it on a branch and send the pull request.

**Comment by adolfo-rt** [comment]
Could we explicitly add the `base_frame_id` to the controller configuration (if not already there)?. I think we are getting to the point where we no longer need our `ros_controllers` fork.

**Comment by efernandez** [comment]
@bmagyar I've just updated the wiki doc http://wiki.ros.org/diff_drive_controller with the new param.
@adolfo-rt I also updated the controller configuration (real robot and gazebo) for REEM, RH2 and mobile base (others don't need it); using `base_footprint`.

**Comment by adolfo-rt** [comment]
:+1:

**Comment by bmagyar** [comment]
:+1:

**Pull request merged**
