### PR TITLE
Create separate headers and document

### PR DESCRIPTION
**Pull request by efernandez**
This keeps the same functionality, but cleans up the code.

### CODE REVIEW

**Comment by po1** [comment]
Please let us know when you are done adding commits ;)

**Comment by efernandez** [comment]
@po1  I've finished with this.

**Comment by po1** [comment]
Doesn't compile anymore.
Report back when it builds and unit tests run.

**Comment by efernandez** [comment]
Now it should compile.

**Comment by po1** [comment]
Rebased on pull request #18, unit tests pass. +1

**Comment by bmagyar** [comment]
+1

**Pull request merged**
