### PR TITLE
Diff drive: test scenarios to exercise controller load failures

### PR DESCRIPTION
**Pull request by po1**
Added two tests:
- controller load failure due to misnamed wheel joint in controller config
- controller load failure due to bad URDF, using spheres instead of cylinders for wheel geometries

This is required for issue #30

### CODE REVIEW

**Comment by po1** [comment]
@adolfo-rt @bmagyar @efernandez

**Comment by adolfo-rt** [comment]
+1

**Comment by bmagyar** [comment]
me gusta +1

**Comment by efernandez** [comment]
late, but :+1: anyway

**Pull request merged**
