### PR TITLE
Diff drive: take odometry parameter multipliers into account

### PR DESCRIPTION
**Pull request by efernandez**
And also rename `cmd_vel_old_threshold` parameter to more meaningful `cmd_vel_timeout`

### CODE REVIEW

**Comment by po1** [comment]
I would have preferred 2 separate commits for the parameter name and the multipliers, but don't bother.

**Comment by po1** [comment]
So that's a :+1: for me.
@adolfo-rt @bmagyar ?

**Comment by bmagyar** [comment]
Seems lke a nice refactoring to me +1

**Comment by po1** [comment]
Wait, stop!
We need to propagate the odometry parameters to the odometry code, line 383.

EDIT: all good. :+1:

**Comment by bmagyar** [comment]
This calls for a merge then.

**Comment by adolfo-rt** [comment]
+1 to exclude C++11, and for the `cmd_vel_timeout` rename. What's missing is extending the test suite to exercise the new code.

**Comment by efernandez** [comment]
That's right. Indeed, the tests are broken. Probably because of the timeout
feature, which should be taken into account.

**Comment by bmagyar** [comment]
The unit tests are not broken since #18 but these features need their own test.

Tests needed:
- wheel separation multiplier
- wheel radius multiplier
- cmd_vel timeout

**Comment by po1** [comment]
- The `cmd_vel_timeout` part of this pull request is now in pull request #21 
- The diff drive parameter multipliers have been applied to commands in 42aa667bfcce58f8f5979b113469b0114d9fd31d, and they are applied to the odometry computation in pull request #22 

Closing this.

**Pull request closed without merging**
