### PR TITLE
Heading normalization not needed

### PR DESCRIPTION
**Pull request by efernandez**
This is done for the Runge-Kutta 2nd order integration, but we didn't do it for the exact integration.

Note that in any case, if we don't normalize the angle, the odometry that is finally published uses a quaternion for the heading, so it gets always normalized at that point (I've verified this on the robot).

### CODE REVIEW

**Comment by po1** [comment]
So since the heading in radians is only used internally, and that we always use it through trigonometric functions, why do we need to normalize it?

**Comment by efernandez** [comment]
@po1 Either we do in both integration methods, or in none.
Doing it in one, but not in the other looks confusing.

The question is then: what is better, normalize or not?
Letting `heading_` grow without bound could affect the precision significantly?

**Comment by po1** [comment]
Like I said, `cos()` and `sin()` will yield the same output regardless of how many times you add `2*pi` to their operand. The only possible issue would be an overflow.

I calculated, it would take approximately 4,649,728,264.69 years of spinning at 10 turns/s to reach this limit.

I would get rid of both. If this is the only place where we use `angles`, then we can get rid of a dependency.

**Comment by efernandez** [comment]
I've just updated the PR: title and removing the normalization.

**Comment by po1** [comment]
Much better!

:+1:

**Comment by adolfo-rt** [comment]
LGTM

**Pull request merged**
