### PR TITLE
No push_back in Real Time

### PR DESCRIPTION
**Pull request by efernandez**
This avoids push_back memory allocations as suggested by @lucamarchionni; although in this case it's only one, the first time is called.

### CODE REVIEW

**Comment by po1** [comment]
looks good to me

**Comment by adolfo-rt** [comment]
Good that you caught this.

> ...although in this case it's only one, the first time is called.

It can still cause undesired behaviour in the system, even if it's only once. If the controller is started while others were already running, this allocation could cause hiccups in the already running ones.

**Comment by po1** [comment]
I'll run a test on ural to get some stats.

**Comment by lucamarchionni** [comment]
nice!

**Comment by bmagyar** [comment]
+1

**Comment by po1** [comment]
Looks ok. Merging.

**Pull request merged**
