### PR TITLE
Add topics to controller node handle

### PR DESCRIPTION
**Pull request by efernandez**
This has been done to be consistent with all the other controllers; they should be in controller_nh instead of root_nh.

### CODE REVIEW

**Comment by po1** [comment]
Gosh, that was a quick merge. By the time I got the mail desktop notification it was already closed.

**Comment by po1** [comment]
Also I don't agree on the _consistency_.
The force_torque_sensor_controller uses root_nh to publish.
The joint_state_controller also uses root_nh to publish.

**Comment by adolfo-rt** [comment]
We can spend some time discussing the policy. This is how I see it:
- The **root namespace** contains robot-specific, controller-agnostic ROS interfaces.
- The **controller namespace** contains controller-specific ROS interfaces. Since it's nested inside the root namespace, the controller interfaces are also robot-specific.

Read-only controllers (they're not really controllers per-se) publishing the state of hardware interfaces (joint_states, force-torque, imu, ...) are a particular case, and can be subject to debate. For instance, /joint_states contains the measured pos,vel,eff of the _entire_ robot, so it makes sense to have it in the root namespace. A similar argument can be applied to the force-torque and imu sensors, there's one topic per hardware interface.

Controllers that actually move hardware are a different story IMO. For them I favor having all the ROS interfaces in the controller namespace.

**Comment by po1** [comment]
I agree with you Adolfo.
As said during our live session, I only regret that __controller_ was used as a suffix for things that only read and publish information without performing any kind of control.

Also, as we said, we could also close our eyes, think hard and imagine a robot that would have more than one diff-drive controller. In that case, the namespacing makes sense.

**Comment by efernandez** [comment]
I also agree, but I have some doubts regarding "read-only contollers":
- If we have more than a single IMU, we'll have to use different namespaces
  for each. Then, we'll have to use the controller namespace, won't we?
- If the IMU is implemented as a controller, should other sensors be
  implemented as well (e.g. rangefinder laser, bumper, etc.)? Certainly, in
  such a case, the _controller suffix would sound quite misleading, but I
  don't thinks is a problem, for the sake of homogeneity and clarity.

2013/10/30 Paul Mathieu notifications@github.com

**Comment by adolfo-rt** [comment]
> - If we have more than a single IMU, we'll have to use different namespaces for each. Then, we'll have to use the controller namespace, won't we?

This is already the case for the force-torque sensor, for which we have two. For IMUs and force-torque sensors, the implementation exposes as many topics as sensors of that type, each named as the sensor. For REEM-C this maps to `left_ft`, `right_ft`, and `base_imu`. If additional namespacing is required, we can open the discussion in a ros_control issue. Any changes in this respect would have to go to indigo-devel, as they break existing ROS APIs.

> - If the IMU is implemented as a controller, should other sensors be implemented as well (e.g. rangefinder laser, bumper, etc.)? 

The only sensors that we currently pass through ros_control are those that allow processing in realtime, that is, that have a realtime driver and churn out data at 100s of Hz or more. The read-only controllers just forward this data to the ROS world at a lower frequency. Lasers, cameras, sonars and bumpers are sensors with lower refresh rates (10s of Hz), hence can be directly exposed by means of a topic.

> Certainly, in such a case, the _controller suffix would sound quite misleading, but I don't thinks is a problem, for the sake of homogeneity and clarity.

I don't like the controller suffix either, but it was already there when we got to ros_control. I guess it is so because the first implementation, the `joint_state_controller` package could not be named `joint_state_publisher` because that package already exists and does something else. I'm still open to discussion in all of this.

**Pull request merged**
