### PR TITLE
Add velocity rolling window size param

### PR DESCRIPTION
**Pull request by efernandez**
Because sometimes 10 is not enough... or too much! ;)

### CODE REVIEW

**Comment by efernandez** [comment]
@lucamarchionni @bmagyar 
Note that this only affects the velocities, not the pose/state.
Anyway, I think is good to have it, and it doesn't change any previous behavior.

**Comment by bmagyar** [comment]
:+1:

**Comment by efernandez** [comment]
BTW, although I used to have write access to merge pull requests, it seems that now I don't...
So, could you merge it for me, or give me access? :)

**Comment by adolfo-rt** [comment]
Merging, as those in the know have +1 the patch

**Comment by adolfo-rt** [comment]
Nevermid, already merged :-P

**Pull request merged**
