### PR TITLE
Speed Limiters

### PR DESCRIPTION
**Pull request by efernandez**
Adds velocity and acceleration limits.

Note that for the acceleration we need the previous velocity.
We take it from the odometry.

### CODE REVIEW

**Comment by po1** [comment]
About getting the speed from the odometry, that is fine, but we had a similar discussion about the joint limits interface, and I'd like to point out that we could also use an open-loop policy and store the last command that we sent to use as a `v0`

**Comment by adolfo-rt** [comment]
AFAIK, we have a lag of ~5 control cycles between sending a command and seeing it executed. If this lag can negatively affect the odometry computation, I'd go for an open-loop solution. We could also test both alternatives in the robot to see how they compare.

**Comment by efernandez** [comment]
All comments have been taken into account and implemented.

@po1  Regarding the open-loop policy, please create a new issue to implement it. I think we should provide a parameter to select the policy, shouldn't we?

**Comment by po1** [comment]
Here begins parameter hell.

**Comment by po1** [comment]
I'll be a bit picky, but can we have a unit test for these limits?

**Comment by bmagyar** [comment]
+1 for the unit tests

**Comment by bmagyar** [comment]
This needs a manual rebase now and some tests.
-     \* @param [in] has_velocity_limits     if true, applies velocity limits
-     \* @param [in] has_acceleration_limits if true, applies acceleration limits
-     \* @param [in] min_velocity Minimum velocity [m/s], usually <= 0
-     \* @param [in] max_velocity Maximum velocity [m/s], usually >= 0
-     \* @param [in] min_acceleration Minimum acceleration [m/s^2], usually <= 0
-     \* @param [in] max_acceleration Maximum acceleration [m/s^2], usually >= 0

These 6 factors could be gathered in 2 tests:
- velocity
- acceleration

**Comment by po1** [comment]
Rebased in another pull request, please continue the discussion in #19

**Pull request closed without merging**
